/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Maysa
 */
public class DescarteView extends javax.swing.JFrame {

    /**
     * Creates new form localizar
     */
    public DescarteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonLocaliza = new javax.swing.JButton();
        buttoInicio = new javax.swing.JButton();
        buttonColeta = new javax.swing.JButton();
        buttonEco = new javax.swing.JButton();
        buttonDescarte = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonLocaliza.setBorder(null);
        buttonLocaliza.setContentAreaFilled(false);
        buttonLocaliza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLocaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLocalizaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonLocaliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 420, 110));

        buttoInicio.setBorder(null);
        buttoInicio.setContentAreaFilled(false);
        buttoInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoInicioActionPerformed(evt);
            }
        });
        jPanel1.add(buttoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 420, 110));

        buttonColeta.setBorder(null);
        buttonColeta.setContentAreaFilled(false);
        buttonColeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonColeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonColetaActionPerformed(evt);
            }
        });
        jPanel1.add(buttonColeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 420, 110));

        buttonEco.setBorder(null);
        buttonEco.setContentAreaFilled(false);
        buttonEco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonEco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEcoActionPerformed(evt);
            }
        });
        jPanel1.add(buttonEco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 420, 110));

        buttonDescarte.setBorder(null);
        buttonDescarte.setContentAreaFilled(false);
        buttonDescarte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonDescarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDescarteActionPerformed(evt);
            }
        });
        jPanel1.add(buttonDescarte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 420, 110));

        jTextField2.setBackground(new java.awt.Color(105, 99, 71));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 240, 188));
        jTextField2.setText("Fulana de tal");
        jTextField2.setToolTipText("");
        jTextField2.setBorder(null);
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 260, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/menu.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/descarte.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1920, 1080));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoInicioActionPerformed
       InicioView teladeinicio = new InicioView();
       teladeinicio.setVisible(true);
       dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttoInicioActionPerformed

    private void buttonColetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonColetaActionPerformed
       ColetaView teladecoleta = new ColetaView();
       teladecoleta.setVisible(true);
       dispose();  
    }//GEN-LAST:event_buttonColetaActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void buttonLocalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLocalizaActionPerformed
       LocalizaView teladelocalizar = new LocalizaView();
       teladelocalizar.setVisible(true);
       dispose();
    }//GEN-LAST:event_buttonLocalizaActionPerformed

    private void buttonDescarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDescarteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDescarteActionPerformed

    private void buttonEcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEcoActionPerformed
       EcoView telaeco = new EcoView();
       telaeco.setVisible(true);
       dispose();
    }//GEN-LAST:event_buttonEcoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DescarteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DescarteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DescarteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DescarteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DescarteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttoInicio;
    private javax.swing.JButton buttonColeta;
    private javax.swing.JButton buttonDescarte;
    private javax.swing.JButton buttonEco;
    private javax.swing.JButton buttonLocaliza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
